---
title: "functions"
author: "Amanda B. Young"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(roxygen2)
```

# Create some data for examples

```{r data-entry}
airtemps<- c(212, 3.3, 75, 32)
airtemp1<- (airtemps[1]-32)*5/9
airtemp2<- (airtemps[2]-32)*5/9
airtemp3<- (airtemps[3]-32)*5/9
airtemp4<- (airtemps[4]-32)*5/9

```

# Write a function for F to C conversion

```{r temp-funct-C}
#' Convert from Fahrenheit to Celsius
#' 
#' A much more detailed explination of how the function works.
#' This could be a paragraph or two!
#' @param fahr represents a numeric input in degrees Fahrenheit
#' @returns the temperature in Celsius
#' @export 
#' @example fahr_to_celcius(212)
#'

fahr_to_celsius <- function(fahr){
  # check if fahr is numeric
  # stopifnot(!is.numeric(fahr))
  celsius <- (fahr - 32)*5/9
  return(celsius)
}

celsius <- fahr_to_celsius(airtemps)
celsius

```

```{r temp-funct-F}
#' Convert from Celsius to Fahrenheit
#' 
#' A much more detailed explination of how the function works.
#' This could be a paragraph or two!
#' @param fahr represents a numeric input in degrees Celsius
#' @returns the temperature in Fahrenheit
#' @export 
#' @example celcius_to_fahr(100)
#'
celsius_to_fahr <- function(cel){
  far<-(cel *9/5)+32
  return(far)
  
}

fahr<-celsius_to_fahr(celsius)
fahr
```

