---
title: "My Webpage"
author: "Amanda B. Young"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries, warning = FALSE, message = FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
```



Download the data
```{r data-download}
esc<-read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", method="libcurl" ), stringsAsFactors=FALSE)

head(esc)
```

# Calculate Annual Escapement for Salmon Species

```{r clean-data, results = "hide"}
species_list<-c("Chinook", "Sockeye", "Chum", "Pink", "Coho")

annual_esc<-esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-",remove=FALSE) %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Year, SASAP.Region, Species) %>% 
  summarise(annual_count = sum(DailyCount)) %>% 
  #filter(Species %in% c("Chinook", "Sockeye", "Chum", "Pink", "Coho"))
  #filter(Species == "Chinook" | Species == "Sockeye")
  filter(Species %in% species_list)

head(annual_esc)
```

# Visualize Escapement
Total Escapment by Region and Species
```{r ggplot, echo = FALSE}
ggplot(annual_esc, aes(x=Species, y=annual_count))+
  #geom_point(aes(colour=SASAP.Region))
  geom_col(aes(fill=SASAP.Region, colour=SASAP.Region))
```
Kodiak Escapment Over Time by Species
```{r}

my_theme<- 
  theme_bw()+
  theme(legend.position = "bottom")
ggplot(data = filter(annual_esc, SASAP.Region == "Kodiak"), aes(x=Year, y=annual_count, colour=Species))+
  geom_point()+geom_line()+
  ylab("Escapment (no. fish)")+
  ggtitle("Kodiak Salmon Escapement")+
  my_theme
```
```{r, fig.width = 7, fig.height = 12}
ggplot(data = annual_esc, aes(x=Year, y=annual_count, colour=Species))+
  geom_point()+geom_line()+
  ylab("Escapment (no. fish)")+
  ggtitle("Kodiak Salmon Escapement")+
  my_theme +
  facet_wrap(.~SASAP.Region, scales="free_y", ncol=1)
```


# Map Sampling Locations
```{r}

```

